/*
 * Copyright 2011 the original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.opencredo.couchdb.core;

import java.net.URI;

/**
 * A POJO representing a change event on a document in the database.
 * </p>
 * Instances of ChangedDocument are immutable.
 *
 * @author Tareq Abedrabbo
 * @since 24/01/2011
 */
public class ChangedDocument {
    /**
     * The nature of change on a document.
     */
    public enum Status {
        CREATED, UPDATED, DELETED;
    }

    private final URI uri;

    private final Status status;

    private final Long sequence;

    /**
     * The unique constructor to create a ChangedDocument.
     *
     * @param uri      the URI of the changes document.
     *                 Example: http://127.0.0.1:5984/mydatabase/f958e9b0-bde6-429e-b4b3-a360a1bfe0a1
     * @param status   the nature of the change event: created, deleted or updated
     * @param sequence the sequence number generated by CouchDB for this change
     */
    public ChangedDocument(URI uri, Status status, Long sequence) {
        this.status = status;
        this.uri = uri;
        this.sequence = sequence;
    }

    /**
     * Returns the URI of the document
     */
    public URI getUri() {
        return uri;
    }

    /**
     * Returns the status of the document
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Returns the CouchDB sequence number of the document
     */
    public Long getSequence() {
        return sequence;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        ChangedDocument that = (ChangedDocument) o;

        if (sequence != null ? !sequence.equals(that.sequence) : that.sequence != null) return false;
        if (status != that.status) return false;
        if (uri != null ? !uri.equals(that.uri) : that.uri != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = uri != null ? uri.hashCode() : 0;
        result = 31 * result + (status != null ? status.hashCode() : 0);
        result = 31 * result + (sequence != null ? sequence.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "ChangedDocument{" +
                "sequence=" + sequence +
                ", uri=" + uri +
                ", status=" + status +
                '}';
    }
}
